# Generated by Django 2.1.15 on 2021-10-25 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departments',
            old_name='DepartName',
            new_name='DepartmentName',
        ),
    ]
